Repository replicatedhq/replicated, pull requests merged in 2022-11, with the labels that each got.

#215 Add endpoint flag to ECR registries
  cli/cmd/registry_add_ecr.go
Labels: type::bug, bug::normal

#207 :book: update readme to improve getting started
  README.md
Labels: type::chore, type::docs

#217 replace pact broker username/password with token
  .github/workflows/main.yaml
  .github/workflows/release.yml
Labels: type::chore
