Repository replicatedhq/replicated, pull requests merged in 2023-10, with the labels that each got.

#329 Joshd/sc 89455/default cluster version for create
  cli/cmd/cluster_create.go
  cli/cmd/cluster_prepare.go
Labels: type::feature

#330 Add GitHub/CI info when in CI
  pkg/platformclient/client.go
Labels: type::feature

#331 Validate Helm chart before creating release
  cli/cmd/release_create.go
Labels: type::bug, bug::normal

#332 Support for setting tags when creating a cluster
  cli/cmd/cluster_create.go
  cli/cmd/runner.go
  cli/print/clusters.go
  pkg/kotsclient/cluster_create.go
  pkg/types/cluster.go
Labels: type::feature

#334 send version info to stderr
  pkg/version/version.go
Labels: type::chore

#335 Use builders linter if release has charts only
  cli/cmd/release_lint.go
Labels: type::bug, bug::normal
