Repository replicatedhq/replicated, pull requests merged in 2023-03, with the labels that each got.

#230 Inconsistent channel info 63010
  cli/cmd/channel_counts.go
  cli/cmd/channel_create.go
  cli/cmd/channel_inspect.go
  cli/cmd/channel_ls.go
  cli/cmd/channel_releases.go
  cli/cmd/customer_create.go
  cli/cmd/release_create.go
  cli/cmd/release_promote.go
  cli/print/channel_attributes.go
  client/channel.go
  pkg/kotsclient/channel.go
  pkg/kotsclient/channel_test.go
  pkg/shipclient/channel.go
  pkg/types/channel.go
Labels: type::bug, bug::normal

#231 Add GCR endpoint
  cli/cmd/registry_add_gcr.go
Labels: type::bug, bug::normal

#232 Remove Ship code
  CONTRIBUTING.md
  cli/cmd/channel_adoption.go
  cli/cmd/channel_counts.go
  cli/cmd/channel_releases.go
  cli/cmd/entitlements.go
  cli/cmd/entitlements_definefields.go
  cli/cmd/entitlements_getcustomerrelease.go
  cli/cmd/entitlements_setvalue.go
  cli/cmd/release_create.go
  cli/cmd/release_promote.go
  cli/cmd/root.go
  client/app.go
  client/channel.go
  client/client.go
  client/collector.go
  client/customer.go
  client/entitlements.go
  client/entitlements/README.md
  client/entitlements/premclient.go
  client/installer.go
  client/release.go
  pacts/replicated-cli-vendor-graphql-api.json
  pkg/shipclient/app.go
  pkg/shipclient/channel.go
  pkg/shipclient/collector.go
  pkg/shipclient/entitlement.go
  pkg/shipclient/entitlement_test.go
  pkg/shipclient/release.go
  pkg/shipclient/release_test.go
Labels: type::chore

#234 cluster ls: fix output
  cli/print/clusters.go
Labels: type::bug

#236 record previous release support ended in Pact on new release [sc-73526]
  .github/workflows/release.yml
  .github/workflows/require-pr-labels.yml
  Makefile
Labels: type::chore
