Repository replicatedhq/replicated, pull requests merged in 2023-07, with the labels that each got.

#262 Adding command to list supported distributions and versions
  cli/cmd/cluster_ls.go
  cli/cmd/cluster_versions.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/clusters.go
  pkg/kotsclient/cluster_versions.go
  pkg/types/cluster.go
Labels: type::feature

#280 Add support to specifying the license type when creating
  cli/cmd/customer_archive.go
  cli/cmd/customer_create.go
  cli/cmd/customer_ls.go
  cli/cmd/release_create.go
  cli/cmd/release_promote.go
  cli/cmd/runner.go
  client/channel.go
  client/customer.go
  pkg/kotsclient/customer_list.go
Labels: type::feature

#281 Rename field from vcpus to vcpu
  cli/cmd/cluster_create.go
Labels: type::feature

#283 Adding space between versions
  cli/print/clusters.go
Labels: type::chore

#285 Allow customers assigned to test customers to not have a channel
  cli/cmd/customer_create.go
  pkg/kotsclient/customer_create.go
Labels: type::feature

#284 Fixing expires_at if not defined
  cli/print/clusters.go
  pkg/types/cluster.go
Labels: type::bug, bug::normal

#279 Adds functionality to display customers and their instances for a specific app version
  cli/cmd/customer_ls.go
  cli/cmd/runner.go
  cli/print/customers.go
  client/customer.go
  pkg/kotsclient/customer_list_by_app_version.go
  pkg/types/customer.go
  pkg/types/instance.go
Labels: type::feature

#282 Adding a prepare cluster cli
  README.md
  cli/cmd/cluster_create.go
  cli/cmd/cluster_prepare.go
  cli/cmd/root.go
  cli/cmd/runner.go
  client/release.go
  go.mod
  go.sum
  pkg/kotsclient/release.go
  pkg/types/customer.go
  pkg/types/release.go
Labels: type::feature

#286 Use a server supplied ttl default
  cli/cmd/cluster_create.go
Labels: type::feature

#287 As requested, change the --appversion flag to be --app-version instead
  cli/cmd/customer_ls.go
Labels: type::chore

#290 Change defaults to 4x16x50
  cli/cmd/cluster_create.go
Labels: type::feature

#289 Add CLI customer inspect command with helm instructions
  cli/cmd/customer_inspect.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/customer_attributes.go
  pkg/kotsclient/channel.go
  pkg/kotsclient/custom_hostname.go
  pkg/types/channel.go
  pkg/types/custom_hostname.go
  pkg/types/customer.go
Labels: type::feature

#292 Allow --chart for premium user but include message
  cli/cmd/release_create.go
Labels: type::bug, bug::normal

#288 Using get cluster vs list
  cli/cmd/cluster_create.go
  pkg/kotsclient/cluster_get.go
Labels: type::chore
