Repository replicatedhq/replicated, pull requests merged in 2023-09, with the labels that each got.

#319 feat (c11y): cluster upgrades
  cli/cmd/cluster_create.go
  cli/cmd/cluster_upgrade.go
  cli/cmd/root.go
  cli/cmd/runner.go
  pkg/kotsclient/cluster_create.go
  pkg/kotsclient/cluster_upgrade.go
  pkg/kotsclient/release_compatibility.go
  pkg/types/cluster.go
Labels: type::feature

#321 Fix customer archive bug
  cli/cmd/customer_archive.go
  cli/cmd/customer_download_license.go
  cli/cmd/customer_inspect.go
  cli/cmd/runner.go
  client/customer.go
  pkg/kotsclient/customer_list.go
Labels: type::bug, bug::normal

#320 Fixes the watch flag output
  cli/cmd/cluster_ls.go
  cli/cmd/release_compatibility.go
  cli/print/clusters.go
  cli/print/util.go
Labels: type::bug, bug::normal

#324 chore (cmx): unhide cluster upgrade command
  cli/cmd/cluster_upgrade.go
Labels: type::chore

#325 fix (cmx): make cluster upgrade arg consistent
  cli/cmd/cluster_upgrade.go
Labels: type::chore

#323 Adding logout command
  cli/cmd/logout.go
  cli/cmd/root.go
  pkg/credentials/credentials.go
Labels: type::feature

#307 Fix instance type example
  cli/cmd/cluster_create.go
Labels: bug::normal, type::chore

#326 Joshd/sc 88868/reject requests for vm clusters with 1 nodes
  cli/cmd/cluster_create.go
  cli/cmd/cluster_ls.go
  cli/cmd/cluster_rm.go
  cli/cmd/cluster_versions.go
  cli/print/clusters.go
  pkg/kotsclient/cluster_create.go
  pkg/kotsclient/cluster_upgrade.go
  pkg/kotsclient/release_compatibility.go
  pkg/types/cluster.go
Labels: type::feature

#327 Pretty print errors when creating customers
  cli/cmd/customer_create.go
  cli/print/customers.go
  pkg/platformclient/client.go
Labels: type::feature

#328 Ignore subcharts
  cli/cmd/cluster_prepare.go
  cli/cmd/cluster_prepare_test.go
Labels: type::bug, bug::normal
