Repository replicatedhq/replicated, pull requests merged in 2023-06, with the labels that each got.

#255 Add an 'api get' command
  cli/cmd/api.go
  cli/cmd/api_get.go
  cli/cmd/api_post.go
  cli/cmd/api_put.go
  cli/cmd/root.go
  cli/cmd/runner.go
  pkg/kotsclient/api.go
  pkg/platformclient/client.go
Labels: type::feature

#257 Fixes #256 Channel Inspect default output format
  cli/cmd/channel_inspect.go
  cli/cmd/runner.go
Labels: type::bug, bug::regression

#259 Return an error if an invalid cluster was created
  cli/cmd/cluster_create.go
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/cluster_rm.go
  pkg/kotsclient/cluster_create.go
Labels: type::feature

#260 Relax validation for Builders apps
  cli/cmd/release_create.go
  cli/cmd/release_promote.go
  cli/cmd/release_update.go
Labels: type::feature

#263 Upgrading to go 1.20
  .github/workflows/main.yaml
  .github/workflows/release.yml
  .github/workflows/working.yml
  Dockerfile
  go.mod
  go.sum
  hack/Dockerfile.testing
Labels: type::chore

#261 Add newline to ouput
  cli/cmd/customer_download_license.go
  cli/print/channel_attributes.go
  cli/print/clusters.go
  cli/print/customers.go
  pkg/credentials/fetch.go
Labels: type::bug, bug::normal

#268 Options to get kubeconfig
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/runner.go
Labels: type::feature

#267 Add wait flag to cluster create
  cli/cmd/cluster_create.go
  cli/cmd/runner.go
Labels: type::feature

#271 support for custom instance types
  cli/cmd/cluster_create.go
  cli/cmd/runner.go
  pkg/kotsclient/cluster_create.go
Labels: type::feature

#273 fix the release-support-ended script
  .github/workflows/release.yml
Labels: type::chore

#266 Joshd/sc 74101/credits system
  cli/cmd/cluster_create.go
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/cluster_ls.go
  cli/cmd/runner.go
  pkg/kotsclient/cluster_create.go
  pkg/kotsclient/cluster_list.go
  pkg/types/cluster.go
Labels: type::feature

#270 Fix for help text indent
  cli/cmd/root.go
Labels: type::bug, bug::normal

#272 added watch command to cluster ls
  cli/cmd/cluster_ls.go
  cli/cmd/runner.go
  cli/print/clusters.go
Labels: type::feature

#275 Not an array
  cli/print/clusters.go
Labels: type::feature

#269 Memory should be using GiB
  cli/cmd/cluster_create.go
  cli/cmd/runner.go
  pkg/kotsclient/cluster_create.go
  pkg/types/cluster.go
Labels: type::feature

#276 Require arg of yaml-dir command line parameter to be a file
  cli/cmd/release_create.go
Labels: type::bug, bug::normal

#278 Fix cluster create output
  cli/print/clusters.go
Labels: type::feature

#277 Allow linting Builders apps
  cli/cmd/release_create.go
  cli/cmd/release_lint.go
  cli/cmd/runner.go
  client/release.go
  pkg/kotsclient/release_lint.go
Labels: type::feature
