Repository replicatedhq/replicated, pull requests merged in 2023-12, with the labels that each got.

#344 Create namespace also for helm install
  cli/cmd/cluster_prepare.go
Labels: type::feature

#345 Adding command to update ttl
  cli/cmd/cluster_update.go
  cli/cmd/cluster_update_ttl.go
  cli/cmd/root.go
  cli/cmd/runner.go
  pkg/kotsclient/cluster_update_ttl.go
Labels: type::feature

#346 Joshd/sc 89457/cli make cluster rm accept name
  cli/cmd/cluster.go
  cli/cmd/cluster_create.go
  cli/cmd/cluster_rm.go
  cli/cmd/runner.go
Labels: type::feature

#347 Improved docs on update ttl
  cli/cmd/cluster_update_ttl.go
Labels: type::chore

#348 Fix flag in instructions
  pkg/platformclient/client.go
Labels: type::bug, bug::normal

#349 Add --output flag to various commands
  cli/cmd/app_create.go
  cli/cmd/app_delete.go
  cli/cmd/app_ls.go
  cli/cmd/channel_create.go
  cli/cmd/channel_inspect.go
  cli/cmd/channel_ls.go
  cli/cmd/customer_create.go
  cli/cmd/customer_inspect.go
  cli/cmd/customer_ls.go
  cli/cmd/enterprise_channel_create.go
  cli/cmd/enterprise_channel_ls.go
  cli/cmd/enterprise_channel_update.go
  cli/cmd/enterprise_installer_create.go
  cli/cmd/enterprise_installer_ls.go
  cli/cmd/enterprise_installer_update.go
  cli/cmd/enterprise_policy_create.go
  cli/cmd/enterprise_policy_ls.go
  cli/cmd/enterprise_policy_update.go
  cli/cmd/installer_ls.go
  cli/cmd/registry_add_dockerhub.go
  cli/cmd/registry_add_ecr.go
  cli/cmd/registry_add_gcr.go
  cli/cmd/registry_add_ghcr.go
  cli/cmd/registry_add_other.go
  cli/cmd/registry_add_quay.go
  cli/cmd/registry_ls.go
  cli/cmd/release_create.go
  cli/cmd/release_lint.go
  cli/cmd/release_ls.go
  cli/cmd/release_promote.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/apps.go
  cli/print/channel_attributes.go
  cli/print/channel_attributes_test.go
  cli/print/channels.go
  cli/print/customer_attributes.go
  cli/print/enterprise_channel.go
  cli/print/enterprise_channels.go
  cli/print/enterprise_installer.go
  cli/print/enterprise_installers.go
  cli/print/enterprise_policies.go
  cli/print/enterprise_policy.go
  cli/print/installers.go
  cli/print/lint.go
  cli/print/registries.go
  cli/print/releases.go
  pkg/types/app.go
Labels: type::feature

#350 Adding cluster shell command
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/cluster_shell.go
  cli/cmd/cluster_update_ttl.go
  cli/cmd/cluster_upgrade.go
  cli/cmd/root.go
  cli/cmd/runner.go
  go.mod
  go.sum
Labels: type::feature

#351 BREAKING CHANGE: Add json tags to release type for JSON output
  pkg/types/release.go
Labels: type::bug, bug::normal
