Repository replicatedhq/replicated, pull requests merged in 2023-08, with the labels that each got.

#291 cache update checker info
  .gitignore
  cli/cmd/cluster_prepare.go
  cli/cmd/root.go
  pkg/credentials/credentials.go
  pkg/replicatedfile/cache.go
  pkg/version/version.go
Labels: type::chore

#299 fix: chart prepare cmd
  cli/cmd/cluster_prepare.go
  pkg/kotsclient/release.go
  pkg/types/release.go
Labels: type::feature

#296 Fix forbidden error in cluster create command
  cli/cmd/cluster_create.go
Labels: type::feature

#298 remove vcpus and memory flags
  cli/cmd/cluster_create.go
  cli/cmd/cluster_prepare.go
  cli/cmd/runner.go
  cli/print/clusters.go
  pkg/kotsclient/cluster_create.go
  pkg/types/cluster.go
Labels: type::feature

#300 feat: validate release status during cluster prepare cmd
  cli/cmd/cluster_prepare.go
  cli/cmd/cluster_prepare_test.go
  cli/print/release.go
  client/release.go
  pkg/kots/release/save.go
  pkg/kots/release/save_test.go
  pkg/kotsclient/release.go
  pkg/types/release.go
Labels: type::feature

#304 Remove all clusters
  cli/cmd/cluster_rm.go
  cli/cmd/runner.go
  pkg/kotsclient/cluster_rm.go
Labels: type::feature

#306 Support creating Helm CLI only customers
  cli/cmd/customer_create.go
  cli/cmd/runner.go
  pkg/kotsclient/customer_create.go
Labels: type::feature

#302 feat: execute preflights when running cluster prepare cmd
  Makefile
  cli/cmd/cluster_prepare.go
  go.mod
  go.sum
Labels: type::feature

#308 Don't show kots install commands for Helm channels
  cli/print/channel_attributes.go
  cli/print/channel_attributes_test.go
  cli/print/channels.go
  client/channel.go
  pkg/kotsclient/channel.go
  pkg/types/channel.go
Labels: type::feature

#309 Remove references to app.IsFoundation
  cli/cmd/release_create.go
  cli/cmd/release_lint.go
  cli/cmd/root.go
Labels: type::bug, bug::normal

#310 feat: return human readable err when requesting kubeconfig for cluster not running
  cli/cmd/cluster_create.go
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/cluster_ls.go
  pkg/types/cluster.go
Labels: type::feature

#303 fix: support for non-semver versions in cluster create command
  cli/cmd/cluster_create.go
  cli/cmd/cluster_prepare.go
  cli/print/clusters.go
  pkg/kotsclient/cluster_create.go
Labels: type::feature

#305 feat: cluster prepare with kots app install
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/cluster_prepare.go
  cli/cmd/cluster_prepare_test.go
  cli/cmd/runner.go
  go.mod
  go.sum
  pkg/kotsclient/customer_create.go
  pkg/kotsclient/release.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
  pkg/types/channel.go
  pkg/types/release.go
Labels: type::feature

#312 Making output more consistent
  cli/cmd/cluster_prepare.go
Labels: type::feature

#311 Fixing preflights for helm charts
  cli/cmd/cluster_prepare.go
  pkg/kotsclient/cluster_get.go
Labels: type::bug, bug::normal

#315 chore: [sc-63726] Fix text alignment for autocomplete help command
  cli/cmd/completion.go
Labels: type::chore

#316 Adding instance types to cluster versions command
  cli/print/clusters.go
  pkg/types/cluster.go
Labels: type::feature

#314 Adding c11y results to release inspect
  cli/cmd/cluster_create.go
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/cluster_ls.go
  cli/cmd/cluster_prepare.go
  cli/cmd/cluster_rm.go
  cli/cmd/cluster_versions.go
  cli/cmd/release_compatibility.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/release.go
  pkg/kotsclient/release.go
  pkg/kotsclient/release_compatibility.go
  pkg/platformclient/client.go
  pkg/types/release.go
Labels: type::feature
