Repository replicatedhq/replicated, pull requests merged in 2024-12, with the labels that each got.

#479 Don't list all customers and channels for the customer inspect command
  cli/cmd/customer_inspect.go
  pkg/kotsclient/channel.go
  pkg/kotsclient/customer_list.go
Labels: type::bug, bug::normal

#480 chore(cmx): update cluster subcommand example to use nodegroup ls
  cli/cmd/cluster.go
Labels: type::chore

#481 Remove postgres cluster addon
  cli/cmd/cluster_addon.go
  cli/cmd/cluster_addon_create.go
  cli/cmd/cluster_addon_create_postgres.go
  cli/cmd/root.go
  cli/print/cluster_addons.go
  pkg/kotsclient/cluster_addon_postgres_create.go
  pkg/types/cluster.go
Labels: type::chore

#471 add common aliases
  cli/cmd/app_ls.go
  cli/cmd/channel_ls.go
  cli/cmd/channel_rm.go
  cli/cmd/cluster_addon_ls.go
  cli/cmd/cluster_addon_rm.go
  cli/cmd/cluster_ls.go
  cli/cmd/cluster_nodegroup_ls.go
  cli/cmd/cluster_port_ls.go
  cli/cmd/cluster_port_rm.go
  cli/cmd/cluster_rm.go
  cli/cmd/collection_ls.go
  cli/cmd/collection_rm.go
  cli/cmd/collector_ls.go
  cli/cmd/customer_ls.go
  cli/cmd/enterprise_portal_user_ls.go
  cli/cmd/installer_ls.go
  cli/cmd/instance_ls.go
  cli/cmd/model_ls.go
  cli/cmd/model_rm.go
  cli/cmd/network_ls.go
  cli/cmd/network_rm.go
  cli/cmd/registry_ls.go
  cli/cmd/registry_rm.go
  cli/cmd/release_ls.go
  cli/cmd/vm_ls.go
  cli/cmd/vm_rm.go
Labels: type::feature

#484 Update to golang.org/x/crypto v0.31.0
  go.mod
  go.sum
Labels: type::chore

#486 Add dev mode flag for creating and updating customers
  cli/cmd/customer_create.go
  cli/cmd/customer_update.go
  pkg/kotsclient/customer_create.go
  pkg/kotsclient/customer_update.go
Labels: type::feature
