Repository replicatedhq/replicated, pull requests merged in 2024-01, with the labels that each got.

#352 Instance ls/inspect/tag CLI
  cli/cmd/cluster.go
  cli/cmd/customer_inspect.go
  cli/cmd/instance.go
  cli/cmd/instance_inspect.go
  cli/cmd/instance_ls.go
  cli/cmd/instance_tag.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/instances.go
  client/instance.go
  pkg/kotsclient/cluster_create.go
  pkg/kotsclient/instance.go
  pkg/types/cluster.go
  pkg/types/instance.go
  pkg/types/tag.go
Labels: type::feature

#353 Return timeout exit code in case of wait duration exceeded
  cli/cmd/cluster_create.go
Labels: type::bug, bug::normal

#354 Remove platform GQL and replace with REST
  cli/cmd/collector_update.go
  cli/print/collector.go
  cli/print/collectors.go
  client/collector.go
  pkg/platformclient/collector.go
  pkg/shipclient/collector.go
  pkg/types/collector.go
Labels: type::chore
