Repository replicatedhq/replicated, pull requests merged in 2024-10, with the labels that each got.

#416 Update dependencies to resolve Critical CVEs
  go.mod
  go.sum
Labels: type::chore

#417 Updating the CMX CLI for Cluster/VM/Network
  cli/cmd/cluster.go
  cli/cmd/cluster_addon.go
  cli/cmd/cluster_addon_create.go
  cli/cmd/cluster_addon_create_objectstore.go
  cli/cmd/cluster_addon_create_postgres.go
  cli/cmd/cluster_addon_ls.go
  cli/cmd/cluster_addon_rm.go
  cli/cmd/cluster_create.go
  cli/cmd/cluster_kubeconfig.go
  cli/cmd/cluster_ls.go
  cli/cmd/cluster_nodegroup.go
  cli/cmd/cluster_nodegroup_ls.go
  cli/cmd/cluster_port.go
  cli/cmd/cluster_port_expose.go
  cli/cmd/cluster_port_ls.go
  cli/cmd/cluster_port_rm.go
  cli/cmd/cluster_prepare.go
  cli/cmd/cluster_rm.go
  cli/cmd/cluster_shell.go
  cli/cmd/cluster_update.go
  cli/cmd/cluster_update_nodegroup.go
  cli/cmd/cluster_update_ttl.go
  cli/cmd/cluster_upgrade.go
  cli/cmd/cluster_versions.go
  cli/cmd/network.go
  cli/cmd/network_create.go
  cli/cmd/network_join.go
  cli/cmd/network_ls.go
  cli/cmd/network_rm.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/cmd/vm.go
  cli/cmd/vm_create.go
  cli/cmd/vm_group.go
  cli/cmd/vm_group_ls.go
  cli/cmd/vm_ls.go
  cli/cmd/vm_rm.go
  cli/cmd/vm_update.go
  cli/cmd/vm_update_ttl.go
  cli/cmd/vm_versions.go
  cli/print/clusters.go
  cli/print/util.go
  cli/print/vms.go
  pkg/kotsclient/vm_create.go
  pkg/kotsclient/vm_versions.go
  pkg/types/vm.go
Labels: type::feature

#418 Add update checking, performance improvements
  go.mod
  go.sum
  pkg/replicatedfile/cache.go
  pkg/version/archive/tgz.go
  pkg/version/github.go
  pkg/version/homebrew/homebrew.go
  pkg/version/pkgmgr/pkgmgr.go
  pkg/version/updatechecker.go
  pkg/version/updateinfo.go
  pkg/version/upgrade.go
  pkg/version/usrbin.go
  pkg/version/version.go
Labels: type::chore

#420 Remove Enterprise client
  cli/cmd/enterprise.go
  cli/cmd/enterprise_auth.go
  cli/cmd/enterprise_auth_approve.go
  cli/cmd/enterprise_auth_init.go
  cli/cmd/enterprise_channel.go
  cli/cmd/enterprise_channel_assign.go
  cli/cmd/enterprise_channel_create.go
  cli/cmd/enterprise_channel_ls.go
  cli/cmd/enterprise_channel_rm.go
  cli/cmd/enterprise_channel_update.go
  cli/cmd/enterprise_installer.go
  cli/cmd/enterprise_installer_assign.go
  cli/cmd/enterprise_installer_create.go
  cli/cmd/enterprise_installer_ls.go
  cli/cmd/enterprise_installer_rm.go
  cli/cmd/enterprise_installer_update.go
  cli/cmd/enterprise_policy.go
  cli/cmd/enterprise_policy_assign.go
  cli/cmd/enterprise_policy_create.go
  cli/cmd/enterprise_policy_ls.go
  cli/cmd/enterprise_policy_rm.go
  cli/cmd/enterprise_policy_unassign.go
  cli/cmd/enterprise_policy_update.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/enterprise_channel.go
  cli/print/enterprise_channels.go
  cli/print/enterprise_installer.go
  cli/print/enterprise_installers.go
  cli/print/enterprise_policies.go
  cli/print/enterprise_policy.go
  pkg/enterpriseclient/auth.go
  pkg/enterpriseclient/auth_test.go
  pkg/enterpriseclient/channel.go
  pkg/enterpriseclient/client.go
  pkg/enterpriseclient/client_test.go
  pkg/enterpriseclient/installer.go
  pkg/enterpriseclient/policy.go
  pkg/enterprisetypes/channel.go
  pkg/enterprisetypes/installer.go
  pkg/enterprisetypes/policy.go
  pkg/types/channel.go
Labels: type::chore

#421 Update the customer CLI
  cli/cmd/customer_archive.go
  cli/cmd/customer_create.go
  cli/cmd/customer_download_license.go
  cli/cmd/customer_inspect.go
  cli/cmd/customer_ls.go
  cli/cmd/customer_update.go
  cli/cmd/root.go
  cli/cmd/runner.go
Labels: type::chore

#422 Archive customers
  cli/cmd/customer_archive.go
  cli/cmd/root.go
  client/customer.go
  pkg/kotsclient/customer_list.go
  pkg/kotsclient/errors.go
Labels: type::chore

#423 Adding enterprise portal cmd
  cli/cmd/app.go
  cli/cmd/app_create.go
  cli/cmd/app_ls.go
  cli/cmd/app_rm.go
  cli/cmd/apps.go
  cli/cmd/enterprise_portal_status.go
  cli/cmd/enterpriseportal.go
  cli/cmd/enterpriseportal_status_get.go
  cli/cmd/enterpriseportal_status_update.go
  cli/cmd/root.go
  cli/cmd/runner.go
  pkg/kotsclient/enterprise-portal.go
Labels: type::feature

#425 fix vm versions
  pkg/kotsclient/vm_versions.go
Labels: type::chore

#426 Cache and default app
  cli/cmd/cache_helper.go
  cli/cmd/default.go
  cli/cmd/default_clear.go
  cli/cmd/default_clearall.go
  cli/cmd/default_set.go
  cli/cmd/default_show.go
  cli/cmd/root.go
  pkg/cache/app.go
  pkg/cache/cache.go
Labels: type::feature

#424 Adding invite commands to enterprise portal
  cli/cmd/enterprise_portal_invite.go
  cli/cmd/enterprise_portal_user.go
  cli/cmd/enterprise_portal_user_ls.go
  cli/cmd/root.go
  pkg/kotsclient/enterprise-portal.go
Labels: type::feature

#427 bubble up more detailed git errors
  cli/cmd/release_create.go
Labels: type::chore

#429 Support count flag for vm create
  cli/cmd/vm_create.go
  pkg/kotsclient/vm_create.go
Labels: type::feature

#430 Populate flag variables
  cli/cmd/customer_download_license.go
Labels: type::bug, bug::regression

#431 Use stringVar(p) instead of manually populating variables
  cli/cmd/customer_download_license.go
Labels: type::chore

#432 Revert "Deprecate --chart flag (#413)"
  cli/cmd/cluster_prepare.go
  cli/cmd/release_create.go
  cli/cmd/release_lint.go
  cli/cmd/release_update.go
  cli/cmd/root.go
Labels: type::chore

#433 Bump goreleaser to a recent version
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: type::chore

#436 Add validate dagger function
  Makefile
  dagger/compatibility.go
  dagger/exec_utils.go
  dagger/functionality.go
  dagger/performance.go
  dagger/security.go
  dagger/validate.go
  pact/kotsclient/app_create_test.go
  pact/kotsclient/app_test.go
  pact/kotsclient/channel_test.go
  pact/kotsclient/client_test.go
  pact/kotsclient/installer_test.go
  pact/kotsclient/registry_test.go
  pact/kotsclient/release_test.go
  pact/kotsclient/token_test.go
  pact/platformclient/app_test.go
  pact/platformclient/client_test.go
  pact/platformclient/release_test.go
  pacts/replicated-cli-vendor-api.json
  pkg/version/updateinfo.go
Labels: type::chore

#435 Removing the GitHub Action release workflow
  .github/workflows/release.yml
  .goreleaser.yaml
  CONTRIBUTING.md
  Dockerfile
  cli/test/kots_app_test.go
  deploy/Dockerfile
  examples/enterprise/replicas.opa
Labels: type::chore

#437 Pass output flag to app
  cli/cmd/app_ls.go
Labels: type::bug, bug::regression

#434 Dagger to release
  .goreleaser-nodocker.yaml
  Makefile
  dagger.json
  dagger/.gitattributes
  dagger/.gitignore
  dagger/compatibility.go
  dagger/exec_utils.go
  dagger/functionality.go
  dagger/go.mod
  dagger/go.sum
  dagger/main.go
  dagger/performance.go
  dagger/release.go
  dagger/security.go
  dagger/validate.go
  pact/kotsclient/app_create_test.go
  pact/kotsclient/app_test.go
  pact/kotsclient/channel_test.go
  pact/kotsclient/client_test.go
  pact/kotsclient/installer_test.go
  pact/kotsclient/registry_test.go
  pact/kotsclient/release_test.go
  pact/kotsclient/token_test.go
  pact/platformclient/app_test.go
  pact/platformclient/client_test.go
  pact/platformclient/release_test.go
  pacts/replicated-cli-vendor-api.json
  pkg/version/updateinfo.go
Labels: type::chore

#438 Change 1password vault to production
  Makefile
  dagger/release.go
Labels: type::chore

#441 add this back in case we need to deploy
  .github/workflows/release.yaml
Labels: type::chore

#442 Fix homebrew
  .goreleaser.yaml
Labels: type::chore

#443 add docker back to goreleaser
  .goreleaser.yaml
Labels: type::chore

#444 Remove release workflow
  .github/workflows/release.yaml
Labels: type::chore

#440 Cleanup from first release with dagger
  .github/workflows/main.yaml
  .github/workflows/working.yml
  .goreleaser-nodocker.yaml
  .goreleaser.yaml
  Makefile
  dagger/release.go
  pkg/version/build.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: type::chore

#446 Specify amd64 platform at build
  dagger.json
  dagger/release.go
Labels: type::bug, bug::normal

#447 trim space from commit
  dagger/release.go
Labels: type::chore

#448 Trim additional outputs
  dagger/release.go
Labels: type::chore

#449 Additional cache busting
  dagger/release.go
Labels: type::chore

#450 Fix for git tree dirty
  dagger/release.go
Labels: type::chore

#456 update integration tests for other app commands
  cli/cmd/app_create.go
  cli/cmd/app_rm.go
  cli/cmd/cache_helper.go
  cli/cmd/root.go
  client/client.go
  pact/kotsclient/app_create_test.go
  pact/kotsclient/app_test.go
  pkg/integration/app_test.go
  pkg/integration/integration.go
  pkg/integration/util_test.go
  pkg/kotsclient/app.go
  pkg/kotsclient/app_create.go
  pkg/kotsclient/types/types.go
  pkg/platformclient/client.go
Labels: type::chore

#454 Add noargs settings
  cli/cmd/cluster_create.go
  cli/cmd/vm_create.go
Labels: type::bug, bug::normal

#455 fix min max node count
  cli/cmd/cluster_create.go
Labels: type::bug, bug::normal

#451 return ssh port and endpoint for direct connection
  pkg/types/vm.go
Labels: type::feature

#457 main is spelled differently
  dagger/release.go
Labels: type::chore

#458 Check app has been specified in all commands that use it
  cli/cmd/channel_adoption.go
  cli/cmd/channel_counts.go
  cli/cmd/channel_create.go
  cli/cmd/channel_disable_semantic_versioning.go
  cli/cmd/channel_enable_semantic_versioning.go
  cli/cmd/channel_inspect.go
  cli/cmd/channel_ls.go
  cli/cmd/channel_releases.go
  cli/cmd/channel_rm.go
  cli/cmd/cluster_prepare.go
  cli/cmd/collector_create.go
  cli/cmd/collector_ls.go
  cli/cmd/collector_promote.go
  cli/cmd/customer_archive.go
  cli/cmd/customer_create.go
  cli/cmd/customer_download_license.go
  cli/cmd/customer_inspect.go
  cli/cmd/customer_ls.go
  cli/cmd/customer_update.go
  cli/cmd/installer_ls.go
  cli/cmd/instance_inspect.go
  cli/cmd/instance_ls.go
  cli/cmd/instance_tag.go
  cli/cmd/release_create.go
  cli/cmd/release_download.go
  cli/cmd/release_inspect.go
  cli/cmd/release_lint.go
  cli/cmd/release_ls.go
  cli/cmd/release_promote.go
  cli/cmd/release_update.go
  cli/cmd/release_validate.go
  cli/cmd/runner.go
Labels: type::bug, bug::regression

#445 releasing doc
  CONTRIBUTING.md
Labels: type::chore

#460 Set GORELEASER_CURRENT_TAG for goreleaser
  dagger/release.go
Labels: type::chore

#461 Add local dir to gitignore
  .gitignore
Labels: type::chore

#462 fix cost for vms
  cli/cmd/vm_ls.go
  cli/print/clusters.go
  cli/print/util.go
  cli/print/vms.go
  pkg/types/vm.go
Labels: type::bug, bug::normal

#464 Use correct output flag in customer inspect
  cli/cmd/customer_inspect.go
Labels: type::bug, bug::regression

#465 Use branches to make releases
  dagger/release.go
Labels: type::chore

#466 Fix syntax error
  dagger/release.go
Labels: type::bug, bug::normal

#467 Use last release tag and branch
  dagger/release.go
Labels: type::feature

#468 Use GORELEASER_PREVIOUS_TAG
  dagger/release.go
Labels: type::chore

#469 Fix self-upgrade
  pkg/version/github.go
Labels: type::bug, bug::normal
