Repository replicatedhq/replicated, pull requests merged in 2024-11, with the labels that each got.

#470 Remove ./bin/replicated from build container
  dagger/release.go
Labels: type::bug, bug::normal

#472 Change native to platform
  cli/cmd/root.go
  client/channel.go
  client/collector.go
  client/installer.go
  client/release.go
Labels: type::bug, bug::regression

#473 Joshd/sc 115395/make tunnels work on cmx vms
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/cmd/vm_port.go
  cli/cmd/vm_port_expose.go
  cli/cmd/vm_port_ls.go
  cli/cmd/vm_port_rm.go
  cli/print/vm_ports.go
  pkg/kotsclient/vm_addon_rm.go
  pkg/kotsclient/vm_port_expose.go
  pkg/kotsclient/vm_port_list.go
  pkg/types/vm.go
Labels: type::feature
