Repository replicatedhq/replicated, pull requests merged in 2024-05, with the labels that each got.

#387 allow name flag for updating ttl
  cli/cmd/cluster_update_ttl.go
  cli/cmd/runner.go
Labels: type::feature

#388 Faster app lookup without channel data
  cli/cmd/app_delete.go
  cli/cmd/app_ls.go
  cli/cmd/root.go
  client/app.go
  client/client.go
  pkg/kotsclient/app.go
  pkg/kotsclient/app_test.go
Labels: type::chore

#386 Adding ip-family support
  cli/cmd/cluster_create.go
  cli/cmd/runner.go
  pkg/kotsclient/cluster_create.go
Labels: type::feature

#391 fix(cmx): no NodeGroup.ClusterID
  pkg/types/cluster.go
Labels: type::chore

#390 fix: [sc-98310] Percent sign shows when exiting `shell`
  cli/cmd/cluster_shell.go
Labels: type::bug, bug::normal

#392 Update go mod dependencies
  cli/cmd/cluster_prepare.go
  go.mod
  go.sum
Labels: type::chore
