Repository replicatedhq/replicated, pull requests merged in 2024-09, with the labels that each got.

#409 Adding ws and wss in helper text
  cli/cmd/cluster_port.go
  cli/cmd/cluster_port_expose.go
Labels: type::feature

#410 make nodegroup fields optional
  cli/cmd/cluster_create.go
  cli/cmd/cluster_create_test.go
Labels: type::bug, bug::normal

#411 Use PATCH method to update channels
  pkg/kotsclient/channel.go
  pkg/kotsclient/channel_test.go
  pkg/types/channel.go
Labels: type::bug, bug::normal

#413 Deprecate --chart flag
  cli/cmd/cluster_prepare.go
  cli/cmd/release_create.go
  cli/cmd/release_lint.go
  cli/cmd/release_update.go
  cli/cmd/root.go
Labels: type::chore

#412 Expose overlay network
  pkg/types/cluster.go
Labels: type::feature
