Repository replicatedhq/replicated, pull requests merged in 2025-08, with the labels that each got.

#562 Update help text for vm port
  cli/cmd/vm_port.go
Labels: type::bug, bug::normal

#563 chore: add beta disclaimer to vm commands
  cli/cmd/vm.go
  cli/cmd/vm_create.go
  cli/cmd/vm_endpoints.go
  cli/cmd/vm_ls.go
  cli/cmd/vm_port.go
  cli/cmd/vm_port_expose.go
  cli/cmd/vm_port_ls.go
  cli/cmd/vm_port_rm.go
  cli/cmd/vm_rm.go
  cli/cmd/vm_update.go
  cli/cmd/vm_update_ttl.go
  cli/cmd/vm_versions.go
Labels: type::chore

#565 update a wide range of dependencies
  go.mod
  go.sum
Labels: type::chore

#567 Improve spacing network report output
  cli/cmd/network_report.go
  cli/print/network_reports.go
Labels: type::bug, bug::normal

#570 fixup pact registry tests
  pact/kotsclient/registry_test.go
  pacts/replicated-cli-vendor-api.json
  pkg/kotsclient/registry_add.go
  pkg/types/registry.go
Labels: type::chore

#575 Update rm/test help references to use `name`
  cli/cmd/registry_rm.go
  cli/cmd/registry_validate.go
Labels: type::chore, area/cli

#576 chore: mark network policies beta and network reporting alpha
  cli/cmd/network_update.go
Labels: type::chore

#578 fix(network-report): Show dashes for all unpopulated fields
  cli/print/network_reports.go
Labels: type::bug, bug::normal
