Repository replicatedhq/replicated, pull requests merged in 2025-01, with the labels that each got.

#487 Support creating addons as part of 'cluster create' command
  cli/cmd/cluster_addon_create_objectstore.go
  cli/cmd/cluster_create.go
  cli/cmd/runner.go
Labels: type::chore

#488 bump go-git from v5.12.0 to v5.13.0
  go.mod
  go.sum
Labels: type::chore

#491 Add help text for "replicated default" command
  cli/cmd/default.go
  cli/cmd/default_clear.go
  cli/cmd/default_clearall.go
  cli/cmd/default_set.go
  cli/cmd/default_show.go
  pkg/cache/cache.go
Labels: type::chore

#492 Hide enterprise and unhide channel commands
  cli/cmd/channel_create.go
  cli/cmd/channel_disable_semantic_versioning.go
  cli/cmd/channel_enable_semantic_versioning.go
  cli/cmd/enterpriseportal.go
Labels: type::chore

#493 Unhide release inspect command
  cli/cmd/release_inspect.go
  cli/print/release.go
Labels: type::chore

#495 Fix docs for release download command
  cli/cmd/release_download.go
Labels: type::chore

#494 Add support for install types when creating and updating customers
  cli/cmd/customer_create.go
  cli/cmd/customer_update.go
  pkg/kotsclient/customer_create.go
  pkg/kotsclient/customer_update.go
Labels: type::feature

#496 Add support for demote/un-demote of chan releases
  cli/cmd/channel_release_demote.go
  cli/cmd/channel_release_undemote.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/channel_attributes.go
  client/channel.go
  pkg/kotsclient/channel.go
  pkg/types/channel.go
Labels: type::feature

#500 Add support for aliases when generating doc markdown
  dagger/docs.go
  go.mod
  go.sum
Labels: type::feature

#498 Bump golang.org/x/net to 0.34.0
  go.mod
  go.sum
Labels: type::security

#499 Add network create cli support
  cli/cmd/cluster_addon.go
  cli/cmd/cluster_addon_create_objectstore.go
  cli/cmd/cluster_create.go
  cli/cmd/network_create.go
  cli/cmd/network_ls.go
  cli/cmd/runner.go
  cli/cmd/vm_create.go
  cli/print/networks.go
  pkg/kotsclient/network_create.go
  pkg/kotsclient/network_get.go
  pkg/kotsclient/vm_create.go
  pkg/types/network.go
Labels: type::feature

#501 Bump dagger golang.org/x/net version 0.34.0
  dagger/go.mod
  dagger/go.sum
Labels: type::security

#502 Integration tests
  .github/workflows/main.yaml
  .github/workflows/working.yml
  Makefile
  cli/cmd/app_create.go
  cli/cmd/app_ls.go
  cli/cmd/app_rm.go
  cli/cmd/root.go
  hack/Dockerfile.testing
  pkg/integration/api_test.go
  pkg/integration/app_test.go
  pkg/integration/integration.go
  pkg/integration/util_test.go
  pkg/platformclient/client.go
  pkg/version/version.go
Labels: type::chore

#503 Add network update outbound
  cli/cmd/network.go
  cli/cmd/network_update.go
  cli/cmd/network_update_outbound.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/networks.go
  pkg/kotsclient/network_update_outbound.go
  pkg/types/network.go
Labels: type::feature

#504 Don't include the auto-gen footer in docs
  docs/gen.go
Labels: type::chore

#505 Fix timeout error check
  pkg/version/github.go
  pkg/version/version.go
Labels: type::bug, bug::normal
