Repository replicatedhq/replicated, pull requests merged in 2025-03, with the labels that each got.

#512 Add ssh and scp subcommand
  cli/cmd/root.go
  cli/cmd/vm_scp.go
  cli/cmd/vm_ssh.go
  pkg/kotsclient/vm_common.go
  pkg/kotsclient/vm_scp.go
  pkg/kotsclient/vm_ssh.go
Labels: type::feature

#513 Performance Improvements for CLI Version Checking
  cli/cmd/root.go
  cli/cmd/version.go
  pkg/version/updatecache.go
  pkg/version/updatechecker.go
  pkg/version/updateinfo.go
  pkg/version/version.go
Labels: type::bug, bug::normal

#514 Update all tools to use Go 1.23
  .github/workflows/main.yaml
  Dockerfile
  dagger/docs.go
  dagger/functionality.go
  dagger/release.go
Labels: type::chore

#515 chore(cmx): accept `-o` for `--output`
  cli/cmd/cluster_create.go
  cli/cmd/cluster_ls.go
  cli/cmd/cluster_nodegroup_ls.go
  cli/cmd/cluster_port_expose.go
  cli/cmd/cluster_port_ls.go
  cli/cmd/cluster_port_rm.go
  cli/cmd/cluster_update_nodegroup.go
  cli/cmd/cluster_update_ttl.go
  cli/cmd/cluster_upgrade.go
  cli/cmd/network_create.go
  cli/cmd/network_ls.go
  cli/cmd/vm_create.go
  cli/cmd/vm_ls.go
  cli/cmd/vm_port_expose.go
  cli/cmd/vm_port_ls.go
  cli/cmd/vm_port_rm.go
  cli/cmd/vm_update_ttl.go
Labels: type::chore

#516 Mention that channel names are case sensitive
  cli/cmd/installer_create.go
  cli/cmd/release_create.go
Labels: type::chore

#517 feature(cmx): Add 'network update policy'
  cli/cmd/network_update_outbound.go
  cli/cmd/network_update_policy.go
  cli/cmd/root.go
  cli/cmd/runner.go
  cli/print/networks.go
  pkg/kotsclient/network_update_outbound.go
  pkg/kotsclient/network_update_policy.go
  pkg/types/network.go
Labels: type::feature

#519 bug(cmx): Print to stderr to not break json
  cli/cmd/network_update_outbound.go
Labels: type::bug, bug::normal

#520 Consistent -o and remove duplicate default
  cli/cmd/app_create.go
  cli/cmd/app_ls.go
  cli/cmd/app_rm.go
  cli/cmd/channel_create.go
  cli/cmd/channel_inspect.go
  cli/cmd/channel_ls.go
  cli/cmd/cluster_addon_create_objectstore.go
  cli/cmd/cluster_addon_ls.go
  cli/cmd/cluster_create.go
  cli/cmd/cluster_ls.go
  cli/cmd/cluster_nodegroup_ls.go
  cli/cmd/cluster_port_expose.go
  cli/cmd/cluster_port_ls.go
  cli/cmd/cluster_port_rm.go
  cli/cmd/cluster_update_nodegroup.go
  cli/cmd/cluster_update_ttl.go
  cli/cmd/cluster_upgrade.go
  cli/cmd/cluster_versions.go
  cli/cmd/collection_addmodel.go
  cli/cmd/collection_create.go
  cli/cmd/collection_ls.go
  cli/cmd/collection_removemodel.go
  cli/cmd/collection_rm.go
  cli/cmd/customer_create.go
  cli/cmd/customer_inspect.go
  cli/cmd/customer_ls.go
  cli/cmd/customer_update.go
  cli/cmd/default_set.go
  cli/cmd/default_show.go
  cli/cmd/enterprise_portal_invite.go
  cli/cmd/enterprise_portal_user_ls.go
  cli/cmd/enterpriseportal_status_get.go
  cli/cmd/enterpriseportal_status_update.go
  cli/cmd/installer_ls.go
  cli/cmd/instance_inspect.go
  cli/cmd/instance_ls.go
  cli/cmd/instance_tag.go
  cli/cmd/model_ls.go
  cli/cmd/model_rm.go
  cli/cmd/network_create.go
  cli/cmd/network_ls.go
  cli/cmd/network_update_outbound.go
  cli/cmd/registry_add_dockerhub.go
  cli/cmd/registry_add_ecr.go
  cli/cmd/registry_add_gar.go
  cli/cmd/registry_add_gcr.go
  cli/cmd/registry_add_ghcr.go
  cli/cmd/registry_add_other.go
  cli/cmd/registry_add_quay.go
  cli/cmd/registry_ls.go
  cli/cmd/release_inspect.go
  cli/cmd/release_lint.go
  cli/cmd/release_ls.go
  cli/cmd/vm_create.go
  cli/cmd/vm_ls.go
  cli/cmd/vm_port_expose.go
  cli/cmd/vm_port_ls.go
  cli/cmd/vm_port_rm.go
  cli/cmd/vm_update_ttl.go
  cli/cmd/vm_versions.go
Labels: type::chore

#521 fix:disable vm port expose for wildcard
  cli/cmd/runner.go
  cli/cmd/vm_port_expose.go
  cli/print/vm_ports.go
  pkg/kotsclient/vm_port_expose.go
  pkg/types/vm.go
Labels: type::bug, bug::normal

#522 feat(vm_ssh): support custom identity-file in 'vm ssh' command
  cli/cmd/vm_ssh.go
  pkg/kotsclient/vm_ssh.go
Labels: type::feature

#523 fix: allow promoting to channel by name when channel level rbac restrictions in place
  client/channel.go
Labels: type::bug, bug::normal
