Repository replicatedhq/replicated, pull requests merged in 2025-04, with the labels that each got.

#525 Pin action runner to `ubuntu-24.04` since 20.04 is EOLing
  .github/workflows/main.yaml
Labels: type::chore

#524 Update release instructions
  README.md
Labels: type::chore

#527 Update Go Dependencies & Dagger Config/Engine requirements
  dagger.json
  dagger/go.mod
  dagger/go.sum
  go.mod
  go.sum
Labels: type::security

#529 Add InstanceType field to VM struct
  pkg/types/vm.go
Labels: type::feature

#530 feat(ec): api change to multi-node enabled
  cli/cmd/customer_create.go
  cli/cmd/customer_update.go
  pkg/kotsclient/customer_create.go
  pkg/kotsclient/customer_update.go
  pkg/types/customer.go
Labels: type::feature

#531 add `replicated vm ssh-endpoint` command to print the ssh endpoint of a vm
  cli/cmd/root.go
  cli/cmd/vm_ssh_endpoint.go
  pkg/kotsclient/user.go
Labels: type::feature

#532 Remove `replicated vm ssh`
  cli/cmd/root.go
  cli/cmd/vm_scp.go
  cli/cmd/vm_ssh.go
  pkg/kotsclient/vm_scp.go
  pkg/kotsclient/vm_ssh.go
Labels: type::chore

#534 Optionally send optional values
  cli/cmd/customer_create.go
  cli/cmd/customer_update.go
  pkg/kotsclient/customer_create.go
  pkg/kotsclient/customer_update.go
Labels: type::bug, bug::regression
