Repository replicatedhq/replicated, pull requests merged in 2025-07, with the labels that each got.

#551 fix(cmx): return proper error on vm deadline and print vm info
  cli/cmd/vm_create.go
Labels: type::bug, bug::normal

#552 Divolgin/sc 125919/install and run pktstat bpf to collect network
  cli/cmd/network_report.go
  cli/cmd/root.go
  cli/cmd/runner.go
  pkg/kotsclient/network_report.go
  pkg/types/network.go
Labels: type::feature

#555 chore: update Go and Dagger dependencies
  dagger.json
  dagger/go.mod
  dagger/go.sum
  dagger/release.go
Labels: type::chore

#556 bump go release version
  dagger/release.go
Labels: type::chore

#557 chore(cmx): Make last scheduling status header only -o wide
  cli/print/clusters.go
  cli/print/vms.go
Labels: type::chore

#559 fix(cmx): Use pointer for collect-report bool
  cli/cmd/network_update.go
  pkg/kotsclient/network_update.go
Labels: type::bug, bug::normal

#560 fix: Update golang.org/x/net to v0.38.0 to fix CVE-2025-22872
  go.mod
  go.sum
Labels: type::chore
